# not required, since no releasable libraries
#
# - NEXUS_USERNAME
# - NEXUS_PASSWORD
# - NEXUS_REPO_URL

#
# requires the following gitlab secret variables
#
# - DOCKER_REGISTRY_USERNAME
# - DOCKER_REGISTRY_PASSWORD
# - DOCKER_REGISTRY_EMAIL
# - DOCKER_REGISTRY_NAME        # eg "registry-1.docker.io" (for docker hub)
                                # or "docker-dev.incode.cloud" (eg a cloud-based nexus)
# - DOCKER_REGISTRY_URL         # eg "https://index.docker.io/v1/" (for docker hub)
                                # or "https://repo.incode.cloud/repository/docker-dev/" (eg a cloud-based nexus)
#
# optionally:
#
# - $BUILD_ADDITIONAL_OPTIONS
#

image: maven:3.5.3-jdk-8

before_script:
  - export REVISION=$(date +%Y%m%d.%H%M).$(echo $CI_COMMIT_REF_NAME | awk -F/ '{ print $NF }').$(echo $CI_COMMIT_SHA | cut -c1-8)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  APP_NAME: "ecpcrm"

stages:
  - build-package-push

build-package-push:
  stage: build-package-push
  script:
    - echo "REVISION=$REVISION"
    - >
      mvn $BUILD_ADDITIONAL_OPTIONS \
          --batch-mode \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
          clean install \
          -Drevision=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_NAME/$DOCKER_REGISTRY_USERNAME/$APP_NAME
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
          docker:push@push-image-tagged \
          -pl webapp \
          -Drevision=$REVISION \
          -DskipTests \
          -Dskip.isis-swagger \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$DOCKER_REGISTRY_NAME/$DOCKER_REGISTRY_USERNAME/$APP_NAME \
          -Ddocker-plugin.serverId=docker-registry \
          -Ddocker.registryUrl=$DOCKER_REGISTRY_URL


